name: DisheEvent CI/CD Pipeline

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    types: [ closed ]
    branches: [ master, main, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm run test:ci || true
        
  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run cleanup script
        run: |
          chmod +x scripts/cleanup.sh
          ./scripts/cleanup.sh
      
      - name: Build application
        run: npm run build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            .next
            public
            package.json
            next.config.ts
            scripts
            
  deploy-development:
    needs: build
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'dev') || 
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development')
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      # Update secrets in Google Cloud Secret Manager if needed
      - name: Update Google Cloud Secrets (if changed)
        run: |
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" | gcloud secrets versions add firebase_api_key_dev --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" | gcloud secrets versions add firebase_auth_domain_dev --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" | gcloud secrets versions add firebase_project_id_dev --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" | gcloud secrets versions add firebase_storage_bucket_dev --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" | gcloud secrets versions add firebase_messaging_sender_id_dev --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" | gcloud secrets versions add firebase_app_id_dev --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" | gcloud secrets versions add firebase_measurement_id_dev --data-file=- || true
          fi
          if [[ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}" ]]; then
            echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}" | gcloud secrets versions add firebase_service_account_dev --data-file=- || true
          fi
      
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools@latest
        
      - name: Deploy to Firebase App Hosting (Development)
        run: |
          cp firebase.dev.json firebase.json
          cp apphosting.dev.yaml apphosting.yaml
          firebase deploy --only apphosting --project ${{ secrets.FIREBASE_PROJECT_ID_DEV }} --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
  deploy-production:
    needs: [build, deploy-development]
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')) || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.base_ref == 'master' || github.base_ref == 'main')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_PROD }}
          service_account_key: ${{ secrets.GCP_SA_KEY_PROD }}
          export_default_credentials: true
          
      # Update secrets in Google Cloud Secret Manager if needed
      - name: Update Google Cloud Secrets (if changed)
        run: |
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY_PROD }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY_PROD }}" | gcloud secrets versions add firebase_api_key_prod --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_PROD }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_PROD }}" | gcloud secrets versions add firebase_auth_domain_prod --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID_PROD }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID_PROD }}" | gcloud secrets versions add firebase_project_id_prod --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_PROD }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_PROD }}" | gcloud secrets versions add firebase_storage_bucket_prod --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_PROD }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_PROD }}" | gcloud secrets versions add firebase_messaging_sender_id_prod --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID_PROD }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID_PROD }}" | gcloud secrets versions add firebase_app_id_prod --data-file=- || true
          fi
          if [[ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID_PROD }}" ]]; then
            echo "${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID_PROD }}" | gcloud secrets versions add firebase_measurement_id_prod --data-file=- || true
          fi
          if [[ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}" ]]; then
            echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}" | gcloud secrets versions add firebase_service_account_prod --data-file=- || true
          fi
      
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools@latest
        
      - name: Deploy to Firebase App Hosting (Production)
        run: |
          cp firebase.prod.json firebase.json
          cp apphosting.prod.yaml apphosting.yaml
          firebase deploy --only apphosting --project ${{ secrets.FIREBASE_PROJECT_ID_PROD }} --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}